# Rule 30 Implementation


Python Implementation of Rule30.


Rule:



![Rule Implementation](./rule30.png)



In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Define the Rule Dictionary

## Compute Rule 30

In [112]:
class Compute_Rule30:
    
    def __init__(self, half_length, iterations):
        self.hl = half_length
        self.iters = iterations
        self.current_row = np.hstack([np.zeros(half_length), 1, np.zeros(half_length)])
        self.rules = {'111':0, '110':0, '101':0, '100':1, '011':1, '010':1, '001':1, '000':0}
        self.data = []
        
        
    def run_compute(self):
        sep = ''
        current_row = self.current_row
        data = []
        
                
        for it in range(self.iters):
            next_row = np.array([])

            for i in range(len(current_row)):
                c1, c2, c3 = 0,0,0

                if i == 0:
                    c1 = 0
                    c2 = current_row[i]
                    c3 = current_row[i+1]

                elif i == (len(current_row)-1):
                    c1 = current_row[i-1]
                    c2 = current_row[i]
                    c3 = 0

                else:
                    c1 = current_row[i-1]
                    c2 = current_row[i]
                    c3 = current_row[i+1]

                key = sep.join(list(map(str,[int(c1),int(c2),int(c3)])))
                next_row = np.append(next_row, self.rules[key])

            data.append(next_row)
            current_row = next_row
        
        self.data = data

In [121]:
cr = Compute_Rule30(10,10)
cr.data
cr.run_compute()
cr.data

[array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 0., 0.,
        0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0.,
        0., 0., 0., 0.]),
 array([0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1.,
        0., 0., 0., 0.]),
 array([0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1.,
        1., 0., 0., 0.]),
 array([0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0.,
        0., 1., 0., 0.]),
 array([0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0.,
        1., 1., 1., 0.]),
 array([1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 0., 1.,
      